wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.19.11
    framework: huggingface
    huggingface_version: 4.49.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1747866492
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 77
      3:
      - 16
      - 23
      - 42
      - 55
      4: 3.10.12
      5: 0.19.11
      6: 4.49.0
      8:
      - 2
      - 5
      13: darwin-arm64
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 16
model:
  desc: null
  value: SCN
pde:
  desc: null
  value: WE
experiment:
  desc: null
  value: WE1
base_resolution:
  desc: null
  value:
  - 250
  - 100
super_resolution:
  desc: null
  value:
  - 250
  - 200
neighbors:
  desc: null
  value: 6
time_window:
  desc: null
  value: 25
unrolling:
  desc: null
  value: 1
nr_gt_steps:
  desc: null
  value: 2
