_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 77
            "2":
                - 1
                - 11
                - 49
                - 55
                - 77
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "6": 4.49.0
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": darwin-arm64
architecture:
    value:
        hidden_dim: 128
        temporal_steps: 3
base_resolution:
    value:
        - 250
        - 100
batch_size:
    value: 16
epochs:
    value: 100
learning_rate:
    value: 0.0001
model:
    value: SCN
neighbors:
    value: 6
pde_type:
    value: WE1
super_resolution:
    value:
        - 250
        - 200
time_window:
    value: 25
unrolling:
    value: 1
