_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 77
            "2":
                - 1
                - 11
                - 49
                - 55
                - 77
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "6": 4.49.0
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": darwin-arm64
base_resolution:
    value:
        - 250
        - 100
batch_size:
    value: 16
epochs:
    value: 50
experiment:
    value: WE1
learning_rate:
    value: 0.001
model:
    value: SCN
neighbors:
    value: 6
nr_gt_steps:
    value: 2
pde:
    value: WE
super_resolution:
    value:
        - 250
        - 200
time_window:
    value: 25
unrolling:
    value: 1
